name: predusk
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - icu=78.2=h33c6efd_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgomp=15.2.0=he0feb66_16
  - liblzma=5.8.2=hb03c661_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_16
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.1=h35e630c_1
  - pip=26.0=pyh8b19718_0
  - python=3.10.19=h3c07f61_3_cpython
  - readline=8.3=h853b02a_0
  - setuptools=80.10.2=pyh332efcf_0
  - tk=8.6.13=noxft_h366c992_103
  - tzdata=2025c=hc9c84f9_1
  - wheel=0.46.3=pyhd8ed1ab_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiohttp-retry==2.9.1
      - aiosignal==1.4.0
      - altair==6.0.0
      - annotated-types==0.7.0
      - anyio==4.12.1
      - async-timeout==4.0.3
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.6
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cohere==5.20.2
      - cryptography==46.0.4
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - exceptiongroup==1.3.1
      - fastavro==1.12.1
      - filetype==1.2.0
      - frozenlist==1.8.0
      - fsspec==2026.1.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.29.0
      - google-api-python-client==2.188.0
      - google-auth==2.48.0
      - google-auth-httplib2==0.3.0
      - google-genai==1.61.0
      - google-generativeai==0.8.6
      - googleapis-common-protos==1.72.0
      - greenlet==3.3.1
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httplib2==0.31.2
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==1.3.7
      - idna==3.11
      - jinja2==3.1.6
      - jiter==0.13.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - langchain==1.2.7
      - langchain-classic==1.0.1
      - langchain-cohere==0.5.0
      - langchain-community==0.4.1
      - langchain-core==1.2.7
      - langchain-google-genai==4.2.0
      - langchain-openai==1.1.7
      - langchain-pinecone==0.2.13
      - langchain-text-splitters==1.1.0
      - langgraph==1.0.7
      - langgraph-checkpoint==4.0.0
      - langgraph-prebuilt==1.0.7
      - langgraph-sdk==0.3.3
      - langsmith==0.6.7
      - markupsafe==3.0.3
      - marshmallow==3.26.2
      - multidict==6.7.1
      - mypy-extensions==1.1.0
      - narwhals==2.16.0
      - numpy==2.2.6
      - openai==2.16.0
      - orjson==3.11.6
      - ormsgpack==1.12.2
      - packaging==24.2
      - pillow==12.1.0
      - pinecone==8.0.0
      - pinecone-plugin-assistant==3.0.2
      - pinecone-plugin-interface==0.0.7
      - propcache==0.4.1
      - proto-plus==1.27.0
      - protobuf==5.29.5
      - pyarrow==23.0.0
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pycparser==3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pydeck==0.9.1
      - pyparsing==3.3.2
      - pypdf==6.6.2
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2026.1.15
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rpds-py==0.30.0
      - rsa==4.9.1
      - shellingham==1.5.4
      - simsimd==6.5.12
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.46
      - streamlit==1.53.1
      - tenacity==9.1.2
      - tiktoken==0.12.0
      - tokenizers==0.22.2
      - toml==0.10.2
      - tornado==6.5.4
      - tqdm==4.67.2
      - typer-slim==0.21.1
      - types-pyyaml==6.0.12.20250915
      - types-requests==2.32.4.20260107
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - uritemplate==4.2.0
      - urllib3==2.6.3
      - uuid-utils==0.14.0
      - watchdog==6.0.0
      - websockets==15.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - zstandard==0.25.0
prefix: /home/rocinate/miniconda3/envs/predusk
